In [11]:
!pip install faker pandas numpy

import pandas as pd
import numpy as np
import random
from faker import Faker
from datetime import datetime, timedelta

fake = Faker('id_ID')

Requirement already satisfied: faker in /usr/local/lib/python3.12/dist-packages (40.15.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [12]:
ref_hewan = pd.DataFrame({
    "id_hewan": ["H4-001", "H2-001"],
    "nama_hewan": ["Sapi", "Ayam"],
    "kategori": ["Ruminansia", "Unggas"]
})

ref_hewan

  id_hewan nama_hewan    kategori
0   H4-001       Sapi  Ruminansia
1   H2-001       Ayam      Unggas

In [13]:
import pandas as pd

provinsi_list = [
    "Aceh",
    "Sumatera Utara",
    "Sumatera Barat",
    "Riau",
    "Kepulauan Riau",
    "Jambi",
    "Sumatera Selatan",
    "Bangka Belitung",
    "Bengkulu",
    "Lampung",
    "DKI Jakarta",
    "Jawa Barat",
    "Jawa Tengah",
    "DI Yogyakarta",
    "Jawa Timur",
    "Banten",
    "Bali",
    "Nusa Tenggara Barat",
    "Nusa Tenggara Timur",
    "Kalimantan Barat",
    "Kalimantan Tengah",
    "Kalimantan Selatan",
    "Kalimantan Timur",
    "Kalimantan Utara",
    "Sulawesi Utara",
    "Sulawesi Tengah",
    "Sulawesi Selatan",
    "Sulawesi Tenggara",
    "Gorontalo",
    "Sulawesi Barat",
    "Maluku",
    "Maluku Utara",
    "Papua",
    "Papua Barat",
    "Papua Selatan",
    "Papua Tengah",
    "Papua Pegunungan",
    "Papua Barat Daya"
]

ref_wilayah = pd.DataFrame({
    "id_wilayah": range(1, len(provinsi_list) + 1),
    "provinsi": provinsi_list
})

ref_wilayah

ref_wilayah = pd.DataFrame({
    "id_wilayah": range(1, len(provinsi_list) + 1),
    "provinsi": provinsi_list
})

ref_wilayah

    id_wilayah             provinsi
0            1                 Aceh
1            2       Sumatera Utara
2            3       Sumatera Barat
3            4                 Riau
4            5       Kepulauan Riau
5            6                Jambi
6            7     Sumatera Selatan
7            8      Bangka Belitung
8            9             Bengkulu
9           10              Lampung
10          11          DKI Jakarta
11          12           Jawa Barat
12          13          Jawa Tengah
13          14        DI Yogyakarta
14          15           Jawa Timur
15          16               Banten
16          17                 Bali
17          18  Nusa Tenggara Barat
18          19  Nusa Tenggara Timur
19          20     Kalimantan Barat
20          21    Kalimantan Tengah
21          22   Kalimantan Selatan
22          23     Kalimantan Timur
23          24     Kalimantan Utara
24          25       Sulawesi Utara
25          26      Sulawesi Tengah
26          27     Sulawesi Selatan
27          28    Sulawesi Tenggara
28          29            Gorontalo
29          30       Sulawesi Barat
30          31               Maluku
31          32         Maluku Utara
32          33                Papua
33          34          Papua Barat
34          35        Papua Selatan
35          36         Papua Tengah
36          37     Papua Pegunungan
37          38     Papua Barat Daya

In [14]:
def random_date(start, end):
    delta = end - start
    random_days = random.randint(0, delta.days)
    return start + timedelta(days=random_days)

start_date = datetime(2024, 1, 1)
end_date = datetime(2025, 12, 31)

In [15]:
data_mutasi = []

for i in range(500):
    row = {
        "id_mutasi": f"MUT-{i+1:04d}",
        "tgl_mutasi": random_date(start_date, end_date).strftime("%m/%d/%y"),
        "id_asal": random.choice(ref_wilayah["id_wilayah"]),
        "id_tujuan": random.choice(ref_wilayah["id_wilayah"]),
        "id_hewan": random.choice(ref_hewan["id_hewan"]),
        "jumlah_ekor": random.randint(10, 200)
    }

    # ❗ Inject missing value (5%)
    if random.random() < 0.05:
        row["jumlah_ekor"] = None

    data_mutasi.append(row)

tr_mutasi = pd.DataFrame(data_mutasi)
tr_mutasi.head()

  id_mutasi tgl_mutasi  id_asal  id_tujuan id_hewan  jumlah_ekor
0  MUT-0001   01/13/24       11          5   H4-001        102.0
1  MUT-0002   09/25/24       28         10   H4-001        197.0
2  MUT-0003   09/30/25       27         12   H2-001        107.0
3  MUT-0004   06/24/25       13         38   H4-001        115.0
4  MUT-0005   01/06/24       31         16   H4-001         89.0

In [16]:
data_sakit = []

for i in range(300):
    row = {
        "id_laporan": f"LAP-{i+1:04d}",
        "tgl_lapor": random_date(start_date, end_date).strftime("%m/%d/%y"),
        "id_wilayah": random.choice(ref_wilayah["id_wilayah"]),
        "id_hewan": random.choice(ref_hewan["id_hewan"]),
        "jumlah_gejala": random.randint(1, 50)
    }

    # ❗ Missing value (10%)
    if random.random() < 0.1:
        row["jumlah_gejala"] = None

    data_sakit.append(row)

tr_laporan_sakit = pd.DataFrame(data_sakit)
tr_laporan_sakit.head()

  id_laporan tgl_lapor  id_wilayah id_hewan  jumlah_gejala
0   LAP-0001  10/02/24          17   H4-001            6.0
1   LAP-0002  12/12/24          14   H2-001           36.0
2   LAP-0003  02/06/25          30   H2-001           27.0
3   LAP-0004  12/06/25          19   H4-001            5.0
4   LAP-0005  12/26/25           4   H2-001            6.0

In [17]:
penyakit_map = {
    "H4-001": ["PMK", "LSD", "Anthrax"],
    "H2-001": ["Flu Burung", "Newcastle Disease"]
}

data_lab = []

for i in range(300):
    laporan = random.choice(tr_laporan_sakit["id_laporan"].tolist())
    hewan = random.choice(ref_hewan["id_hewan"])

    row = {
        "id_uji": f"LAB-{i+1:04d}",
        "id_laporan": laporan,
        "tgl_uji": random_date(start_date, end_date).strftime("%m/%d/%y"),
        "penyakit": random.choice(penyakit_map[hewan]),
        "hasil_uji": random.choice(["Positif", "Negatif"])
    }

    # ❗ Missing value di hasil_uji (7%)
    if random.random() < 0.07:
        row["hasil_uji"] = None

    data_lab.append(row)

tr_hasil_lab = pd.DataFrame(data_lab)
tr_hasil_lab.head()

     id_uji id_laporan   tgl_uji           penyakit hasil_uji
0  LAB-0001   LAP-0009  07/21/24            Anthrax   Negatif
1  LAB-0002   LAP-0298  06/17/24  Newcastle Disease      None
2  LAB-0003   LAP-0192  11/29/24  Newcastle Disease   Positif
3  LAB-0004   LAP-0176  08/21/24  Newcastle Disease   Negatif
4  LAB-0005   LAP-0110  07/23/24                PMK   Positif

In [18]:
data_rph = []

for i in range(400):
    hewan = random.choice(ref_hewan["id_hewan"])

    row = {
        "id_potong": f"PTG-{i+1:04d}",
        "tgl_potong": random_date(start_date, end_date).strftime("%m/%d/%y"),
        "id_wilayah": random.choice(ref_wilayah["id_wilayah"]),
        "id_hewan": hewan,
        "berat_karkas": round(random.uniform(5, 300), 2)
    }

    # ❗ Missing value (5%)
    if random.random() < 0.05:
        row["berat_karkas"] = None

    data_rph.append(row)

tr_rph = pd.DataFrame(data_rph)
tr_rph.head()

  id_potong tgl_potong  id_wilayah id_hewan  berat_karkas
0  PTG-0001   11/21/24           4   H2-001         83.41
1  PTG-0002   03/28/25           4   H2-001        120.66
2  PTG-0003   12/20/24          31   H4-001        277.95
3  PTG-0004   12/03/25          34   H2-001         92.51
4  PTG-0005   01/01/25          23   H4-001         31.55

In [19]:
ref_hewan.to_csv("ref_hewan.csv", index=False)
ref_wilayah.to_csv("ref_wilayah.csv", index=False)
tr_mutasi.to_csv("tr_mutasi.csv", index=False)
tr_laporan_sakit.to_csv("tr_laporan_sakit.csv", index=False)
tr_hasil_lab.to_csv("tr_hasil_lab.csv", index=False)
tr_rph.to_csv("tr_rph.csv", index=False)

print("Semua data berhasil disimpan!")

Semua data berhasil disimpan!

In [23]:
!pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.49)
Requirement already satisfied: pymysql in /usr/local/lib/python3.12/dist-packages (1.1.2)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)

### Konfigurasi Koneksi MySQL
Silakan sesuaikan variabel di bawah ini dengan konfigurasi Laragon Anda (biasanya user adalah `root` dan password kosong).

In [26]:
from sqlalchemy import create_engine

# Konfigurasi database
user = 'root'
password = '' # Laragon default kosong
host = '127.0.0.1' # Localhost
port = '3306'
db_name = 'db_kesehatan'

# Membuat engine koneksi
engine = create_engine(f'mysql+pymysql://{user}:{password}@{host}:{port}/{db_name}')

try:
    # Ekspor semua DataFrame ke MySQL
    ref_hewan.to_sql('ref_hewan', con=engine, if_exists='replace', index=False)
    ref_wilayah.to_sql('ref_wilayah', con=engine, if_exists='replace', index=False)
    tr_mutasi.to_sql('tr_mutasi', con=engine, if_exists='replace', index=False)
    tr_laporan_sakit.to_sql('tr_laporan_sakit', con=engine, if_exists='replace', index=False)
    tr_hasil_lab.to_sql('tr_hasil_lab', con=engine, if_exists='replace', index=False)
    tr_rph.to_sql('tr_rph', con=engine, if_exists='replace', index=False)

    print("Semua tabel berhasil dimasukkan ke database MySQL!")
except Exception as e:
    print(f"Terjadi kesalahan: {e}")

Terjadi kesalahan: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [27]:
import sqlite3
import pandas as pd

def generate_sql_script(filename, tables_dict):
    with open(filename, 'w') as f:
        f.write("SET NAMES utf8mb4;\n")
        f.write("SET FOREIGN_KEY_CHECKS = 0;\n\n")

        for table_name, df in tables_dict.items():
            f.write(f'DROP TABLE IF EXISTS `{table_name}`;\n')

            # Create table syntax with backticks and MySQL friendly types
            schema = pd.io.sql.get_schema(df, table_name)
            schema = schema.replace('"', '`') # Replace double quotes with backticks
            schema = schema.replace('INTEGER', 'INT')
            schema = schema.replace('REAL', 'DOUBLE')
            f.write(f'{schema};\n\n')

            # Insert statements
            for _, row in df.iterrows():
                cols = '`, `'.join(row.index)
                vals = []
                for val in row.values:
                    if pd.isna(val):
                        vals.append('NULL')
                    elif isinstance(val, (int, float)):
                        vals.append(str(val))
                    else:
                        # Escape single quotes for SQL string
                        clean_val = str(val).replace("'", "''")
                        vals.append(f"'{clean_val}'")

                vals_str = ', '.join(vals)
                f.write(f"INSERT INTO `{table_name}` (`{cols}`) VALUES ({vals_str});\n")
            f.write("\n")

        f.write("SET FOREIGN_KEY_CHECKS = 1;\n")

tables = {
    'ref_hewan': ref_hewan,
    'ref_wilayah': ref_wilayah,
    'tr_mutasi': tr_mutasi,
    'tr_laporan_sakit': tr_laporan_sakit,
    'tr_hasil_lab': tr_hasil_lab,
    'tr_rph': tr_rph
}

generate_sql_script('data_peternakan.sql', tables)
print("File 'data_peternakan.sql' telah diperbarui dengan format MySQL! Silakan download kembali.")

File 'data_peternakan.sql' telah diperbarui dengan format MySQL! Silakan download kembali.